### PR TITLE
Move to use of prop-types package for PropTypes

### PR DESCRIPTION
**Pull request by davidfurlong**

### CODE REVIEW

**Comment by bzbetty** [comment]
React 16 is out, this is important for those of us who would like to upgrade.

**Comment by istarkov** [comment]
@bzbetty 
https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L3

**Comment by bzbetty** [comment]
well now i just feel silly =) especially since i bashed my head trying to find an alternative fix for an hour.
thanks heaps!

**Comment by andrevenancio** [comment]
June, July, August, September and now October. Is this going to be merged soon?

**Comment by istarkov** [comment]
This fix affects examples only, and not the library itself. Ill merge when Ill have time, this is very low priority

**Pull request merged**
