### PR TITLE
Support for the definition of basic url

### PR DESCRIPTION
**Pull request by alexey-polushin**

### CODE REVIEW

**Comment by itsmichaeldiego** [comment]
@alexey-polushin Thanks for your contribution. Would you mind telling us why do you need this? Also, there is a problem in Travis, you can check that [here](https://travis-ci.org/istarkov/google-map-react/builds/227608157?utm_source=github_status&utm_medium=notification)

**Comment by itsmichaeldiego** [comment]
@alex-e-leon Feel free to re-open when you can fix the conflicts and provide further information

**Comment by alex-e-leon** [comment]
@itsmichaeldiego I think you've accidentally tagged the wrong person?

**Comment by itsmichaeldiego** [comment]
You're right @alex-e-leon, sorry. 

@alexey-polushin: Feel free to re-open when you can fix the conflicts and provide further information

**Pull request closed without merging**
