### PR TITLE
Add lodash polyfills for Number.isNaN & Number.isFinite

### PR DESCRIPTION
**Pull request by MozMorris**
Pretty self explanatory PR.

### CODE REVIEW

**Comment by istarkov** [comment]
Thank you!, 
but it looks like it's better to use https://lodash.com/docs#isNumber
instead of this
```javascript
function isNumber(n) {
...
 }
```

What do you think?

**Comment by MozMorris** [comment]
Agreed, I've made the change and rebased.

**Comment by istarkov** [comment]
I've add you to project contributors, can you merge this pull request or i need to change any other settings?

**Comment by MozMorris** [comment]
No, looks like I have permission. I'm just a bit scared to press the button! Thanks for adding me to the repos.

**Comment by istarkov** [comment]
Merged :-)
Thank you!!!

**Pull request merged**
