### PR TITLE
Allow user to specify the position

### PR DESCRIPTION
**Pull request by SyedSaifAli**
It is occupying the whole area.
I just wanted to use the map within a region. Not the whole div.

### CODE REVIEW

**Comment by istarkov** [comment]
Within what? What the problem this change could solve?

**Comment by SyedSaifAli** [comment]
Actually, currently the map is visible in the whole page.  Is it possible that I can use the style as I want? Like I don't want the position as absoulte because it is consuming the whole page. What other possible solutions are there?

**Comment by istarkov** [comment]
The other option is to read css spec about position property.

**Comment by SyedSaifAli** [comment]
And how can I do that?

**Comment by SyedSaifAli** [comment]
Hey Ivan.. Your google-map-react module was very good. Can you please tell
me that by using that package can I draw some polylines as I get co
ordinates from the server in real time?

Thanks man

**Pull request closed without merging**
