### PR TITLE
Improve the example code

### PR DESCRIPTION
**Pull request by aaronmader**
Update the example code to include a marker definition (MyGreatPlace) for completeness.
Addresses issue #300

### CODE REVIEW

**Comment by istarkov** [comment]
Thank you! But -

This is readme example. 
- It must be short. 
- Just before example I wrote `you just need to add lat lng props to any child of GoogleMap component`
- At first sentences of readme I wrote `It allows you to render any React component on the Google Map`
- `import` contains `./` which means that it's some your component
- Where are a lot of working examples refs in readme even on `jsbin`.

So sorry I don't think this is needed.

**Comment by aaronmader** [comment]
Solid points.. I did eventually find my way over to https://github.com/istarkov/google-map-react-examples which was a HUGE help. 

I got stuck because I was assuming that there was more to the MyGreatPlace component. (And I suppose that's where the other +1's in the issue were struggling too). You're instruction `you just need to add lat lng props to any child of GoogleMap component` makes sense to me *now*, but at the time I was just trying to copy/paste your example into my react project, without success. 

Maybe if we just add another simple example using a div? (I'll create a pull request to show what I mean)

**Comment by Sapphire64** [comment]
I was thinking about improving that part too and suddenly found this PR already in place :) `MyGreatPlace` has to be explained, for me passing of geo attributes to every kinds of components seems to be unclear (but I agree, this is useful), so I had to dig into examples too. I thought you need to handle the coordinates inside of the component.

So I am +1 on current patch or maybe can suggest to apply following patch to have only one usage of "MyGreatPlace" in the example:
```
- <MyGreatPlace lat={59.955413} lng={30.337844} text={'A'} /* Kreyser Avrora */ />
+ <div lat={59.955413} lng={30.337844}>{'A'}</div> /* Kreyser Avrora */
```

`MyGreatPlace` is also vague to be fair, if we change it to something in the context like `RedMarker` it will explain more that it's a wrapper, not the actual target object with coordinates like you can misunderstand now.

In general I would prefer to have next interface when it comes to markers on the map to make it less confusing:
```
<Marker key={} lat={} lng={}>
    <YourComponentHere/>
</Marker>
```
But that's another story.

**Comment by hjmccain** [comment]
The lack of detail about MyGreatPlace was a source of frustration for me, as well, and led me to initially pass up this module. @istarkov your argument is that the Readme needs to be short — explaining MyGreatPlace module would barely lengthen it at all — four sentences, maybe, and a line or two of code? Worth it for the clarity!

**Comment by hjmccain** [comment]
@aaronmader I'm looking at the pull request you made, but when I try to add a div with lat & lng, the marker is not showing up and I'm getting some complaining from the console — `Warning: Unknown props `lat`, `lng`, `$hover`, `$getDimensions`, `$dimensionKey`, `$geoService`, `$onMouseAllow`, `$prerender` on <div> tag.` If you're around and down to help clarify your code — I'm probably missing something small — I'd really appreciate it!

**Comment by istarkov** [comment]
Thank you all, please look at current readme
https://github.com/istarkov/google-map-react/pull/320

**Pull request closed without merging**
