### PR TITLE
Added support for minZoomOverride flag. If set to true, the minZoom o…

### PR DESCRIPTION
**Pull request by deviantony**
…ption will be used instead of being calculated.

My attempt to get this feature available quickly. See #118 & #146

### CODE REVIEW

**Comment by istarkov** [comment]
Thank you! Please add into readme with warning that in some cases this option could break markers math.

**Comment by deviantony** [comment]
Sure, where do you want me to add this? In the tips section?

**Comment by istarkov** [comment]
It's on you ;-)

**Comment by deviantony** [comment]
All right, here you go :)

**Comment by istarkov** [comment]
Thank you!!! I will publish in 10-15min

**Comment by deviantony** [comment]
:+1:

**Comment by istarkov** [comment]
Should be in npm 0.12.1

**Pull request merged**
