### PR TITLE
Support className prop

### PR DESCRIPTION
**Pull request by glennreyes**
Could be useful 😉

### CODE REVIEW

**Comment by istarkov** [comment]
> Could be useful
Just one case I see, setting `flex:1` ;-) 

I think to remove even style property, also remove internal autoSizer, and to include AutoSizer from react-virtualized library which works well for block and flex containers

**Comment by glennreyes** [comment]
What do you mean by `flex: 1`? 😄 
Imho the wrapper should be as intuitive as possible 👍  What I've just added here was the possibility to define CSS rules via a className. So it saves me one extra div

**Comment by istarkov** [comment]
For me all that `style` and `className` exposing as a props, looks like an antipattern. The best what can do non styled component as like as map is to fit it's parent size. 

The problem that inside `display: flex` container defaults like `width: 100%; height: 100%` will not working, and even you set `flex:1` with `width` and `height` defined this won't help.

So in future version of map component I want to remove `style` prop, and provide an `AutoSizer` as a root map container.

And what the reason to remove additional `div` here, I could understand that for controls like `table` every additional cell `div` can cause performance issues but for controls like map even 10 additional divs around will not affect perf.

**Comment by dverbovyi** [comment]
Hi, I need this feature as well. Is it going to be merged?

**Pull request closed without merging**
