### PR TITLE
Allow gmap option props to be changed dynamically

### PR DESCRIPTION
**Pull request by alex-e-leon**
@istarkov Dynamic map options as per https://github.com/istarkov/google-map-react/pull/197

I was also using the develop section as a simple test playground - if you want to see/use the same you can see the (very simple) tests I was running with [here](https://github.com/alex-e-leon/google-map-react/commit/9ab1a5d7d9b4221e6feebb0e31d5bc8d453f15ca)

### CODE REVIEW

**Comment by jooj123** [comment]
+1

**Comment by istarkov** [comment]
Super! Will publish today evening or tomorrow morning.

**Comment by istarkov** [comment]
And Thank You!!!!

**Comment by alex-e-leon** [comment]
no problem

**Comment by istarkov** [comment]
in npm 0.17.0

**Pull request merged**
