### PR TITLE
fix issue #23

### PR DESCRIPTION
**Pull request by jedwards1211**
Link: https://github.com/istarkov/google-map-react/issues/23

### CODE REVIEW

**Comment by istarkov** [comment]
Dear Andy i've add you to project collaborators, and you can merge this by yourself. After that i'll do `npm publish`.

**Comment by jedwards1211** [comment]
Cool, thanks!  This has been really useful, glad I can help out!

**Comment by istarkov** [comment]
Thank you, new version available in npm now

**Comment by jedwards1211** [comment]
Thank you!

**Pull request merged**
