### PR TITLE
Add class name to marker

### PR DESCRIPTION
**Pull request by carsy**
It would be nice to have a class added to the marker to be able to animate its position. Even though animating top and left is not the most efficient method ever (transform is more performant) this is a good start (I can work on using transform to position the markers if you think it's a good idea).

### CODE REVIEW

**Comment by istarkov** [comment]
Im not prefer or use global css classnames at all, in all my current work I use css-modules. Also u can always use your marker animation, there is no need to animate component div, just animate your marker.

Also I could change internal lib details significantly, so really can't support this addition.

**Comment by istarkov** [comment]
About left top - cant get your problem. Use transitions with offset on your marker

**Comment by carsy** [comment]
@istarkov I completely agree with you. But ever you ever needed to animate markers in between coords? That's my use case.

**Comment by istarkov** [comment]
Could you provide a real animation description, as I can animate anything independent of root element in most cases, so cant get your case :-(

**Comment by istarkov** [comment]
Also now for a lot of animations I prefer to use react-motion like in cluster example (ref in docs),

**Comment by carsy** [comment]
@istarkov sure thing, I'll get you an example tomorrow (plane trip).

**Comment by istarkov** [comment]
Like here https://github.com/istarkov/google-map-clustering-example/blob/master/src/markers/ClusterMarker.js
For a lot of cases performance is really good, and allows to skip all that css hacks, like recreating elements to disable already running transitions etc. (Like 80% code of old markers is just to support css transitions)

**Comment by carsy** [comment]
So my use case is to animate between two coordinates:

```jsx
<div
  lat={ this.props.position.lat }
  lng={ this.props.position.lng }
/>
```

Every time I call render, the lat and lng are different and I need to animate from the previous position to the new one.

**Comment by istarkov** [comment]
You are right, In your case having className you could just set a transition in css. 
Ill write few moments later how to fix this PR.

**Comment by carsy** [comment]
@istarkov thank you 👍

**Comment by istarkov** [comment]
To make it best, let's pass className for this parent div on a marker, as it will be your class it will not pollute css. Also you could pass this className only for markers you need. (For example you want to animate just one marker)

Example
```javascript
<GMap>
  <MyMarker lat={lat} lng={lng} $markerHolderClassName={classNameForHolder} />
</GMap>
```

As here https://github.com/istarkov/google-map-react/pull/144/files#diff-7474dce7e0c5e0e592c272e34eefa16bR250 you have access to child props, you coud easily add this class. (be sure to not add anything if user has not pass this className)

Also for a time I want this `$markerHolderClassName` to be an `undocumented feature` with `$` char at beginning. (_I don't sure that it's a good idea to provide public access to this feature, until public example with this feature using will be provided_)

Thank you, will wait your PR.

**Comment by carsy** [comment]
@istarkov on it ☺️

**Comment by carsy** [comment]
@istarkov here you go

**Comment by istarkov** [comment]
Cool! Thank you!!!

**Comment by istarkov** [comment]
In npm as `0.12.0`

**Comment by carsy** [comment]
@istarkov awesome 😄  thank you

**Pull request merged**
