### PR TITLE
Allow react 0.14.0-beta1 to be a peer dependency

### PR DESCRIPTION
**Pull request by cgarvis**

### CODE REVIEW

**Comment by jdaily** [comment]
+1

**Comment by jedwards1211** [comment]
@istarkov since you made me a collaborator, do you want me to go ahead and merge pull requests I've tested?  Or let you do it?

**Comment by istarkov** [comment]
@jedwards1211 As a collaborator you can do all what you want.

**Comment by jedwards1211** [comment]
@istarkov cool, thanks!

**Comment by istarkov** [comment]
@jedwards1211 Can you write me smth on my email istarkov@gmail.com and i send you npm login - password so u can publish this via npm?

**Comment by channikhabra** [comment]
I think this isn't published to npm yet. Can you please publish it to npm?

**Comment by istarkov** [comment]
@channikhabra it's in npm, why do you think it's not?

**Comment by istarkov** [comment]
@channikhabra O sorry, not in npm, published just now

**Comment by channikhabra** [comment]
Thanks for prompt response.

**Comment by istarkov** [comment]
@channikhabra Does map work with react 0.14?

**Comment by channikhabra** [comment]
It does with warnings that it should be using `react-dom.render/findDOMNode` instead of `react.reader/findDOMNode`. 

screen shot 2015-09-17 at 2 53 47 pm

**Comment by istarkov** [comment]
Thank you.
Does anybody know how to write library with support of react 0.13 and react 0.14 if where is no `react-dom` for react 0.13.

Do we need use this :-) https://github.com/facebook/react/blob/69ab7145bc36a500195ccf0e2937ded21520582f/src/React.js#L67
```javascript
React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED
```

**Pull request merged**
