### PR TITLE
#add newBounds to fitBounds utils

### PR DESCRIPTION
**Pull request by ipostol**

### CODE REVIEW

**Comment by istarkov** [comment]
Great! Thank you!
please remove `npm-debug.log` from PR and fix linting rules or code to fix travis build `camelcase` error (looks like eslint updated).

**Comment by ipostol** [comment]
I am fix, by disable lines for eslint.

**Comment by istarkov** [comment]
I see, next time I open computer, Ill merge and publish this. (On mobile now)

**Comment by istarkov** [comment]
Thank you once again, best issue is a PR, can't say how much I like such PRs.
Published npm 0.16.1

**Pull request merged**
