### PR TITLE
Add source to clustering example

### PR DESCRIPTION
**Pull request by lloydwatkin**

### CODE REVIEW

**Comment by istarkov** [comment]
why?

**Comment by lloydwatkin** [comment]
Because your other examples have links to the source and this didn't.

**Comment by AlexandreKilian** [comment]
this would be really usefull, since this isn't documented and I can't seem to figure it out with the docs... It'd be nice to map all markers and render a different component depending on if it's a cluster or a single marker

**Comment by Tim152** [comment]
where I can find docs for this clustering example?

**Comment by istarkov** [comment]
Thank you

**Comment by Tim152** [comment]
thank you!  
ohh.. recompose, it's hurt ):

**Pull request merged**
